# Generated by Django 4.2.2 on 2023-06-12 12:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Echo_api', '0002_alter_group_access_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupchat',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_chats', to=settings.AUTH_USER_MODEL),
        ),
    ]
