# Generated by Django 4.2.2 on 2023-06-12 12:59

import Echo_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Echo_api', '0003_alter_groupchat_liked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupchat',
            name='unique_key',
            field=models.CharField(default=Echo_api.models.generate_access_key, max_length=7, unique=True),
        ),
    ]
