# Generated by Django 4.2.2 on 2023-06-12 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Echo_api', '0004_groupchat_unique_key'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroupChat',
        ),
    ]
