# Generated by Django 4.2.2 on 2023-06-12 13:11

import Echo_api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Echo_api', '0005_delete_groupchat'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('unique_key', models.CharField(default=Echo_api.models.generate_access_key, max_length=7, unique=True)),
                ('chatBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Echo_api.group')),
                ('liked_by', models.ManyToManyField(blank=True, related_name='liked_chats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
