# Generated by Django 4.2.2 on 2023-06-13 11:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Echo_api', '0006_groupchat'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='Group_cht_user',
        ),
    ]
